name: to_do
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_slidable: ^4.0.0
  intl: ^0.20.2
  provider: ^6.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/fonts/Poppins-Thin.ttf
    - assets/fonts/Poppins-ExtraLight.ttf
    - assets/fonts/Poppins-Light.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Medium.ttf
    - assets/fonts/Poppins-SemiBold.ttf
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-ExtraBold.ttf
    - assets/fonts/Poppins-Black.ttf
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        # Add other italic variants similarly

flutter_icons:
  android: true
  image_path: "assets/images/logo.png"
